name: study_flash
description: "My Flash Cards App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.4
  cupertino_icons: ^1.0.8
  flip_card: ^0.7.0
  fl_chart: ^1.1.1
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_database: ^12.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.3
  freezed: any
  freezed_annotation: any
  json_annotation: ^4.9.0
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
